version: '3'

services:
  mysql:
    container_name: github-actions_mysql
    image: mysql:8
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]

  rabbitmq:
    container_name: github-actions_rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=github
      - RABBITMQ_DEFAULT_PASS=GitHub

  nginx:
    container_name: github-actions_nginx
    image: nginx:1.26-alpine
    restart: unless-stopped
    ports:
      - "8030:80"
    volumes:
      - .:/app:delegated
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: github-actions_php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9090:9001"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    depends_on:
      - mysql
      - rabbitmq