name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hello world!
        run: echo "Hello!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: More info about current job
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job context: $JOB_CONTEXT"
          echo "Done!"

      - uses: actions/cache@v3
        with:
          path: ~/.composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os}}-composer-
      

      - name: Install dependencies
        run: make composer-install

      - name: Start all the environment
        run: make start

      - name: Run tests
        run: make test
